# Generated by Django 4.1.5 on 2023-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnandQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
